# Android
# Build your Android project with Gradle.
# Add steps that test, sign, and distribute the APK, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/android

trigger:
- main

pool:
  name: Default

pr:
- none

variables:
- name: build_country
  value: none

steps:
- task: Bash@3
  displayName: Get the build country
  inputs:
    targetType: inline
    script: |
      BUILD_COUNTRY=`cat opensrp-reveal/build.gradle | grep BUILD_COUNTRY | head -n 1 | awk {'print $4'} | awk -F'.' {'print tolower($6)'} | sed 's/"//'`
      echo $BUILD_COUNTRY
      echo "##vso[task.setvariable variable=build_country]$BUILD_COUNTRY"
- task: Bash@3
  displayName: Set the build number to version number
  inputs:
    targetType: inline
    script: sed -i 's/BUILD_NUMBER/$(build_country).$(Build.BuildId)/' opensrp-reveal/build.gradle
- task: CopyFiles@2
  displayName: Copy the google-services.json
  inputs:
    SourceFolder: '/opt/'
    Contents: 'google-services.json'
    TargetFolder: 'opensrp-reveal'
    OverWrite: true
- task: CmdLine@2
  displayName: Copy the local.properties
  inputs:
    script: cp /opt/reveal-client-config/$(build_country).properties local.properties
- task: Gradle@2
  displayName: Build the APK
  inputs:
    workingDirectory: ''
    gradleWrapperFile: 'gradlew'
    gradleOptions: '-Xmx3072m'
    publishJUnitResults: false
    testResultsFiles: '**/TEST-*.xml'
    tasks: 'clean build'
    options: '-x test'
- task: Bash@3
  displayName: Sign and zip the APK
  inputs:
    targetType: inline
    script: jarsigner -keystore /opt/reveal-client-config/keystore.jks -storepass $(jarsignerKeystorePassword) opensrp-reveal/build/outputs/apk/release/opensrp-reveal-release-unsigned.apk akros.online && /home/fanie/Android/Sdk/build-tools/29.0.3/zipalign 4 opensrp-reveal/build/outputs/apk/release/opensrp-reveal-release-unsigned.apk opensrp-reveal/build/outputs/apk/release/reveal-release-$(build_country)-$(Build.BuildId).apk
- task: CopyFiles@2
  displayName: Gather the debug apk
  inputs:
    SourceFolder: 'opensrp-reveal/build/outputs/apk/debug/'
    Contents: 'opensrp-reveal-debug.apk'
    TargetFolder: 'opensrp-reveal/build/outputs/apk/upload'
    OverWrite: true
- task: CmdLine@2
  displayName: Rename the debug apk
  inputs:
    script: mv opensrp-reveal/build/outputs/apk/upload/opensrp-reveal-debug.apk opensrp-reveal/build/outputs/apk/upload/reveal-debug-$(build_country)-$(Build.BuildId).apk
- task: CopyFiles@2
  displayName: Gather the release apk
  inputs:
    SourceFolder: 'opensrp-reveal/build/outputs/apk/release/'
    Contents: 'reveal-release-$(build_country)-$(Build.BuildId).apk'
    TargetFolder: 'opensrp-reveal/build/outputs/apk/upload'
    OverWrite: true
- task: UniversalPackages@0
  displayName: Upload the APK
  inputs:
    command: publish
    publishDirectory: opensrp-reveal/build/outputs/apk/upload/
    vstsFeedPublish: 'Reveal/reveal-client-release'
    vstsFeedPackagePublish: 'reveal-release-$(build_country)-$(Build.BuildId).apk'
    packagePublishDescription: 'reveal-release-$(build_country)-$(Build.BuildId).apk'